// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl24zo1sG8vdv3fM2rqyceQMCQfPHrxLY',
    appId: '1:592836621600:web:60e95bb59d1c6501951345',
    messagingSenderId: '592836621600',
    projectId: 'chat-app-7ab9f',
    authDomain: 'chat-app-7ab9f.firebaseapp.com',
    storageBucket: 'chat-app-7ab9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF0Uh0m2_xilq-__IpNOsHPCWGiGp8BIk',
    appId: '1:592836621600:android:9fc06e958b41ec7e951345',
    messagingSenderId: '592836621600',
    projectId: 'chat-app-7ab9f',
    storageBucket: 'chat-app-7ab9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwxQHs7lS9dAqUGN3l5tRi9VmZK6J9L3Q',
    appId: '1:592836621600:ios:30f91cd78311d328951345',
    messagingSenderId: '592836621600',
    projectId: 'chat-app-7ab9f',
    storageBucket: 'chat-app-7ab9f.appspot.com',
    iosClientId: '592836621600-7b2onoihqb6ut9eugj34thq0juua83il.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwxQHs7lS9dAqUGN3l5tRi9VmZK6J9L3Q',
    appId: '1:592836621600:ios:30f91cd78311d328951345',
    messagingSenderId: '592836621600',
    projectId: 'chat-app-7ab9f',
    storageBucket: 'chat-app-7ab9f.appspot.com',
    iosClientId: '592836621600-7b2onoihqb6ut9eugj34thq0juua83il.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
